// AUTO-GENERATED by swap-images — do not edit by hand.
// Toggled by: node swap-images.mjs <original|watermark> [template]
//   watermark mode -> true (overlay shown)   original mode -> false (overlay off)
export const WATERMARK = true;
